{% set version = "1.11" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ddpcr
  version: {{ version|replace("-", "_") }}

source:
  fn: ddpcr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ddpcr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ddpcr/ddpcr_{{ version }}.tar.gz
  sha256: 9967c6850010f0ce5dd99ab7dd0223d766272a2a579c991cb0b60e216e7f8e6a

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dt >=0.2
    - r-dplyr >=0.5.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval >=0.1.10
    - r-magrittr >=1.5
    - r-mixtools >=1.0.2
    - r-plyr >=1.8.1
    - r-readr >=0.1.0
    - r-shiny >=0.11.0
    - r-shinyjs >=0.4.0
  run:
    - r-base
    - r-dt >=0.2
    - r-dplyr >=0.5.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval >=0.1.10
    - r-magrittr >=1.5
    - r-mixtools >=1.0.2
    - r-plyr >=1.8.1
    - r-readr >=0.1.0
    - r-shiny >=0.11.0
    - r-shinyjs >=0.4.0

test:
  commands:
    - $R -e "library('ddpcr')"           # [not win]
    - "\"%R%\" -e \"library('ddpcr')\""  # [win]

about:
  home: https://github.com/daattali/ddpcr
  license: MIT
  summary: An interface to explore, analyze, and visualize droplet digital PCR (ddPCR) data in
    R. This is the first non-proprietary software for analyzing two-channel ddPCR data.
    An interactive tool was also created and is available online to facilitate this
    analysis for anyone who is not comfortable with using R.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
