{% set version = "1.15.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ddpcr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ddpcr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ddpcr/ddpcr_{{ version }}.tar.gz
  sha256: 2b8c72cafc735b6f5e316a197754f7e6ef9ba578e732660f92d2d821982f42ab

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dt >=0.2
    - r-dplyr >=0.5.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval >=0.1.10
    - r-magrittr >=1.5
    - r-mixtools >=1.0.2
    - r-plyr >=1.8.1
    - r-readr >=0.1.0
    - r-shiny >=0.11.0
    - r-shinydisconnect
    - r-shinyjs >=0.4.0
    - r-tibble
  run:
    - r-base
    - r-dt >=0.2
    - r-dplyr >=0.5.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval >=0.1.10
    - r-magrittr >=1.5
    - r-mixtools >=1.0.2
    - r-plyr >=1.8.1
    - r-readr >=0.1.0
    - r-shiny >=0.11.0
    - r-shinydisconnect
    - r-shinyjs >=0.4.0
    - r-tibble

test:
  commands:
    - $R -e "library('ddpcr')"           # [not win]
    - "\"%R%\" -e \"library('ddpcr')\""  # [win]

about:
  home: https://github.com/daattali/ddpcr
  license: MIT
  summary: An interface to explore, analyze, and visualize droplet digital PCR (ddPCR) data in R. This is the first non-proprietary software for analyzing two-channel ddPCR data. An interactive tool was also created and is available online to facilitate this analysis for anyone who is not comfortable with using R.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ddpcr
# Title: Analysis and Visualization of Droplet Digital PCR in R and on the Web
# Version: 1.15
# Authors@R: c( person("Dean", "Attali", email = "daattali@gmail.com", role = c("aut", "cre")) )
# Description: An interface to explore, analyze, and visualize droplet digital PCR (ddPCR) data in R. This is the first non-proprietary software for analyzing two-channel ddPCR data. An interactive tool was also created and is available online to facilitate this analysis for anyone who is not comfortable with using R.
# URL: https://github.com/daattali/ddpcr
# BugReports: https://github.com/daattali/ddpcr/issues
# Depends: R (>= 3.1.0)
# Imports: DT (>= 0.2), dplyr (>= 0.5.0), ggplot2 (>= 2.2.0), lazyeval (>= 0.1.10), magrittr (>= 1.5), mixtools (>= 1.0.2), plyr (>= 1.8.1), readr (>= 0.1.0), shiny (>= 0.11.0), shinyjs (>= 0.4.0), tibble
# Suggests: ggExtra (>= 0.3.0), graphics, grid (>= 3.2.2), gridExtra (>= 2.0.0), knitr (>= 1.7), rmarkdown, stats, testthat (>= 0.11.0), utils
# License: MIT + file LICENSE
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-06-02 02:09:55 UTC; D
# Author: Dean Attali [aut, cre]
# Maintainer: Dean Attali <daattali@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-06-02 07:10:07 UTC
