appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iPD0juIpMzsJTQjSGPcpEEUG9J+CZWL4FG/gZqhBuf5VasJYdkvo7jCh8ghkYbcb1VS2on8oFMl2U6bGQu86PvqdGH+fdaONGeppZ+rLBACGwDxgMZ1rxJ5mlWeGqpLs+7kzfnBTjhlRm5u+M0/+h6Xjsf+pV4+4CjBq3XPKc2Vd82PDJo+0EDN2QeIpjF9NxO+jcHt0Ak1+BXNDmUkb6LF8E+j+cqkhBKouQzge7WL9+IHRbhER/LlTBdUVva+aaxOXosofZ0Awrz6m+ZtfNU4v9u+QFGwg4yPHrT9NE9JdyPY8JY7k77Tu3aJvWL5iyJIodffDY6P5NgNoNKFY31QKnKwtNhqP2ueM6X/JPTmzpyuNtMYyiQ+bmqM2h2kIK44uq6U+zGXxJEQ1XEE8QZBR0RV6Wf6SQYry2w2frL6+bbvxVrqlfH9F50uvvL8kMX8uQUlkLLjiP7owk3cjUkR3qf+uuZS/8oIjNeapAGmxj7RLZ4gbAhLMpd50RfqYOWl59RCqTiUU+v0Emiov1z9JXwlB6gaOOscPkbA/OICSwERB2Mi6nfemv/pLHIB/t/Ww7ViJ3Sfx2QjzxY6rom7z/DdpScax/zhqaL7CgRrFJTFCwb83favxtUWZX4zGsgBsiDglTmguIp2ySWQbuf/9IXnepqbKQOqt0L9I+Ls=}
